@baseUrl = http://localhost:3000
@blogsUrl = {{baseUrl}}/api/blogs

### Get all blogs
GET {{blogsUrl}}

### Create a new blog
##### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "johndoe@john.com",
  "password": "mysecretpassword"
}
##### create blog
POST {{blogsUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiam9obmRvZUBqb2huLmNvbSIsImlhdCI6MTczMjE4MTc2M30.tDLPRVCwPzPO8DRHnthbyoJzCi6inp4oo7XonCGIia8

{
  "author": "John Doe",
  "url": "https://example.com/new-blog",
  "title": "My new blog post",
  "likes": 0
}

### Update blog likes
PUT {{blogsUrl}}/14
Content-Type: application/json

{
  "likes": 5
}

### Delete a blog
DELETE {{blogsUrl}}/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiam9obmRvZUBqb2huLmNvbSIsImlhdCI6MTczMjE4MTc2M30.tDLPRVCwPzPO8DRHnthbyoJzCi6inp4oo7XonCGIia8


###########################################
#### TEST ####

### Create a new blog with bad format
POST {{blogsUrl}}
Content-Type: application/json

{
  "auth": "John Doe",
  "uri": "https://example.com/new-blog",
  "title": "My new blog post",
  "likes": 0
}

### Update blog likes with wrong format
PUT {{blogsUrl}}/10
Content-Type: application/json

{
  "like": 5
}

### Update blog likes with non existing id
PUT {{blogsUrl}}/100
Content-Type: application/json

{
  "like": 5
}