@baseUrl = http://localhost:3000/api
@readinglist = {{baseUrl}}/readinglists

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "johndoe@john.com",
  "password": "mysecretpassword"
}

### extracting token
@token = Bearer {{login.response.body.token}}

### add reading list
POST {{readinglist}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}  

{
  "userId": 1,
  "blogId": 1
}

### update readinglist
PUT {{readinglist}}/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "read": true
}


#############################################
### Test

### update readinglist without token
PUT {{readinglist}}/1 HTTP/1.1
Content-Type: application/json

{
  "read": true
}
