@baseUrl = http://localhost:3000/api
@userUrl = {{baseUrl}}/users

### Get all users
GET {{userUrl}}

### Get single user
GET {{userUrl}}/1

### Create a new user
POST {{userUrl}}
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johndoe@john.com",
  "password": "mysecretpassword"
}

### Update a user's username
PUT {{userUrl}}/johndoe@john.com
Content-Type: application/json

{
  "username": "newjohndoe2@john.com"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "johndoe@john.com",
  "password": "mysecretpassword"
}

#########################################
#### Test ####

### Create a new user using bad username
POST {{userUrl}}
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johndoe",
  "password": "mysecretpassword"
}